/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as GoalsGoalIdRouteImport } from './routes/goals.$goalId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as FinanceIncomeIncomeIdRouteImport } from './routes/finance.income.$incomeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsGoalIdRoute = GoalsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => GoalsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const FinanceIncomeIncomeIdRoute = FinanceIncomeIncomeIdRouteImport.update({
  id: '/income/$incomeId',
  path: '/income/$incomeId',
  getParentRoute: () => FinanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRouteWithChildren
  '/goals': typeof GoalsRouteWithChildren
  '/learning': typeof LearningRoute
  '/notes': typeof NotesRoute
  '/planning': typeof PlanningRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/finance/income/$incomeId': typeof FinanceIncomeIncomeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRouteWithChildren
  '/goals': typeof GoalsRouteWithChildren
  '/learning': typeof LearningRoute
  '/notes': typeof NotesRoute
  '/planning': typeof PlanningRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/finance/income/$incomeId': typeof FinanceIncomeIncomeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/auth': typeof AuthRoute
  '/finance': typeof FinanceRouteWithChildren
  '/goals': typeof GoalsRouteWithChildren
  '/learning': typeof LearningRoute
  '/notes': typeof NotesRoute
  '/planning': typeof PlanningRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/routines': typeof RoutinesRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/goals/$goalId': typeof GoalsGoalIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/finance/income/$incomeId': typeof FinanceIncomeIncomeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/auth'
    | '/finance'
    | '/goals'
    | '/learning'
    | '/notes'
    | '/planning'
    | '/profile'
    | '/projects'
    | '/reset-password'
    | '/routines'
    | '/settings'
    | '/tasks'
    | '/goals/$goalId'
    | '/projects/$projectId'
    | '/finance/income/$incomeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/auth'
    | '/finance'
    | '/goals'
    | '/learning'
    | '/notes'
    | '/planning'
    | '/profile'
    | '/projects'
    | '/reset-password'
    | '/routines'
    | '/settings'
    | '/tasks'
    | '/goals/$goalId'
    | '/projects/$projectId'
    | '/finance/income/$incomeId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/auth'
    | '/finance'
    | '/goals'
    | '/learning'
    | '/notes'
    | '/planning'
    | '/profile'
    | '/projects'
    | '/reset-password'
    | '/routines'
    | '/settings'
    | '/tasks'
    | '/goals/$goalId'
    | '/projects/$projectId'
    | '/finance/income/$incomeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AuthRoute: typeof AuthRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  GoalsRoute: typeof GoalsRouteWithChildren
  LearningRoute: typeof LearningRoute
  NotesRoute: typeof NotesRoute
  PlanningRoute: typeof PlanningRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoutinesRoute: typeof RoutinesRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals/$goalId': {
      id: '/goals/$goalId'
      path: '/$goalId'
      fullPath: '/goals/$goalId'
      preLoaderRoute: typeof GoalsGoalIdRouteImport
      parentRoute: typeof GoalsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/finance/income/$incomeId': {
      id: '/finance/income/$incomeId'
      path: '/income/$incomeId'
      fullPath: '/finance/income/$incomeId'
      preLoaderRoute: typeof FinanceIncomeIncomeIdRouteImport
      parentRoute: typeof FinanceRoute
    }
  }
}

interface FinanceRouteChildren {
  FinanceIncomeIncomeIdRoute: typeof FinanceIncomeIncomeIdRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceIncomeIncomeIdRoute: FinanceIncomeIncomeIdRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface GoalsRouteChildren {
  GoalsGoalIdRoute: typeof GoalsGoalIdRoute
}

const GoalsRouteChildren: GoalsRouteChildren = {
  GoalsGoalIdRoute: GoalsGoalIdRoute,
}

const GoalsRouteWithChildren = GoalsRoute._addFileChildren(GoalsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AuthRoute: AuthRoute,
  FinanceRoute: FinanceRouteWithChildren,
  GoalsRoute: GoalsRouteWithChildren,
  LearningRoute: LearningRoute,
  NotesRoute: NotesRoute,
  PlanningRoute: PlanningRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RoutinesRoute: RoutinesRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
